package org.hinsteny.dal.mapper;

import org.hinsteny.model.dos.UserDO;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_user
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_user
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    int deleteByPrimaryKey(String id);

}