package org.hinsteny.model.dos;

import java.util.Date;

public class UserDO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.id
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.mobile
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.avatar
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.sex
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.nickname
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.type
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.gmt_create
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_user.gmt_modified
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.id
     *
     * @return the value of tf_user.id
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.id
     *
     * @param id the value for tf_user.id
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.mobile
     *
     * @return the value of tf_user.mobile
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.mobile
     *
     * @param mobile the value for tf_user.mobile
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.avatar
     *
     * @return the value of tf_user.avatar
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.avatar
     *
     * @param avatar the value for tf_user.avatar
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.sex
     *
     * @return the value of tf_user.sex
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.sex
     *
     * @param sex the value for tf_user.sex
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.nickname
     *
     * @return the value of tf_user.nickname
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.nickname
     *
     * @param nickname the value for tf_user.nickname
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.type
     *
     * @return the value of tf_user.type
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.type
     *
     * @param type the value for tf_user.type
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.gmt_create
     *
     * @return the value of tf_user.gmt_create
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.gmt_create
     *
     * @param gmtCreate the value for tf_user.gmt_create
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_user.gmt_modified
     *
     * @return the value of tf_user.gmt_modified
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_user.gmt_modified
     *
     * @param gmtModified the value for tf_user.gmt_modified
     *
     * @mbg.generated Sat Feb 03 17:54:56 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}